//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teatro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegranteInstrumentoPuestoEvento
    {
        public int Id { get; set; }
        public int EventoId { get; set; }
        public int PuestoId { get; set; }
        public int IntegranteId { get; set; }
        public int InstrumentoId { get; set; }
        public System.DateTime FechaInscripcion { get; set; }
        public System.DateTime FechaBaja { get; set; }
        public bool Activo { get; set; }
    
        public virtual Evento Evento { get; set; }
        public virtual Instrumento Instrumento { get; set; }
        public virtual Integrante Integrante { get; set; }
        public virtual Puesto Puesto { get; set; }
    }
}
